additionalProperties: false
type: object
description: 'An object describing a Platform role.'
required:
  - name
properties:
  name:
    $ref: '#/components/schemas/NameField'
  id:
    type: string
    description: 'The role ID. May alse be ''none'', ''admin'', or ''base_app_user'' default roles.'
    readOnly: true
    minLength: 4
    maxLength: 24
  type:
    type: string
    description: 'The type of Role. Only ''userInApp'' is currently available.'
    enum:
      - userInApp
  version:
    type: integer
    description: 'The Role API version.'
    enum:
      - 2
  description:
    $ref: '#/components/schemas/DescriptionField'
  customFields:
    $ref: '#/components/schemas/CustomFieldsDocument'
  scopes:
    $ref: '#/components/schemas/RoleScopesDocument'
  createdAt:
    $ref: '#/components/schemas/CreatedAtField'
  updatedAt:
    $ref: '#/components/schemas/UpdatedAtField'
