additionalProperties: false
type: object
description: 'An object representing a platform product. Product can have identifiers. Identifiers
which have keys mentioned in account unique identifiers configuration will be concatenated and
used as unique identifier for a given product which means that user will not be able to create
two products with the same unique identifiers.'
required:
  - name
properties:
  name:
    $ref: '#/components/schemas/NameField'
  id:
    $ref: '#/components/schemas/IdField'
  createdAt:
    $ref: '#/components/schemas/CreatedAtField'
  updatedAt:
    $ref: '#/components/schemas/UpdatedAtField'
  activatedAt:
    type: integer
    description: 'Timestamp when the product was activated.'
    readOnly: true
  description:
    $ref: '#/components/schemas/DescriptionField'
  type:
    $ref: '#/components/schemas/TypeField'
  categories:
    description: 'An array of product categories as strings.'
    type: array
    items:
      type: string
  photos:
    description: 'An array of product photo URLs as strings.'
    type: array
    items:
      type: string
  url:
    type: string
    description: 'The URL linking to the product information.'
  identifiers:
    $ref: '#/components/schemas/IdentifiersDocument'
  properties:
    type: object
    description: 'A JSON object with key-value pairs describing properties of the product.'
  tags:
    $ref: '#/components/schemas/TagsDocument'
  customFields:
    $ref: '#/components/schemas/CustomFieldsDocument'
  fn:
    type: string
    description: 'Friendly name of the product.'
    readOnly: true
  brand:
    type: string
    description: 'The product''s brand name.'
  scopes:
    $ref: '#/components/schemas/ScopesDocument'
x-filterable-fields:
  - name: 'name'
    type: 'string'
    operators:
      - '='
  - name: 'identifiers.<key>'
    type: 'string'
    operators:
      - '='
  - name: 'tags'
    type: 'list of string'
    operators:
      - '='
