get:
  tags:
    - Applications
  summary: 'Read Trusted App API Key'
  description: 'Read the Trusted Application API key for the application with `applicationId`. This is a secret key that has access to more endpoints than the standard Application API key.'
  parameters:
    -
      $ref: '#/components/parameters/projectId'
    -
      $ref: '#/components/parameters/applicationId'
  responses:
    '200':
      description: 'The Trusted Application API key.'
      content:
        application/json:
          schema:
            type: object
          example:
            secretApiKey: oEdxM3LcE351wLg1Zb2co6KmCLGIIUDmUNVKqbjb...
  x-api-keys:
    - Operator
